name: Rails CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.10'
          bundler-cache: true

      - name: Prepare test database
        run: bundle exec rails db:schema:load

      - name: Run tests
        run: bundle exec rails test
